In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
from sklearn.preprocessing import LabelEncoder

In [25]:
le = LabelEncoder()

In [26]:
df = pd.read_csv("student_performance_dataset.csv")

In [27]:
df

Student_ID  Gender  Study_Hours_per_Week  Attendance_Rate  \
0         S147    Male                    31        68.267841   
1         S136    Male                    16        78.222927   
2         S209  Female                    21        87.525096   
3         S458  Female                    27        92.076483   
4         S078  Female                    37        98.655517   
..         ...     ...                   ...              ...   
703       S492    Male                    14        84.658761   
704       S301    Male                    35        60.278990   
705       S473    Male                    25        98.384969   
706       S307  Female                    21        96.148012   
707       S046  Female                    22        80.404392   

     Past_Exam_Scores Parental_Education_Level Internet_Access_at_Home  \
0                  86              High School                     Yes   
1                  73                      PhD                      No   
2                  74                      PhD                     Yes   
3                  99                Bachelors                      No   
4                  63                  Masters                      No   
..                ...                      ...                     ...   
703                78                      PhD                     Yes   
704                83                  Masters                      No   
705                75                Bachelors                     Yes   
706                84                Bachelors                     Yes   
707                93                Bachelors                     Yes   

    Extracurricular_Activities  Final_Exam_Score Pass_Fail  
0                          Yes                63      Pass  
1                           No                50      Fail  
2                           No                55      Fail  
3                           No                65      Pass  
4                          Yes                70      Pass  
..                         ...               ...       ...  
703                         No                50      Fail  
704                         No                62      Pass  
705                         No                57      Fail  
706                         No                65      Pass  
707                         No                55      Fail  

[708 rows x 10 columns]

In [28]:
df.columns

Index(['Student_ID', 'Gender', 'Study_Hours_per_Week', 'Attendance_Rate',
       'Past_Exam_Scores', 'Parental_Education_Level',
       'Internet_Access_at_Home', 'Extracurricular_Activities',
       'Final_Exam_Score', 'Pass_Fail'],
      dtype='object')

In [29]:
updated_df= df.drop(columns=['Student_ID', 'Gender',
       'Past_Exam_Scores', 'Parental_Education_Level',
       'Internet_Access_at_Home', 'Extracurricular_Activities',
       'Final_Exam_Score'])

In [30]:
updated_df

Study_Hours_per_Week  Attendance_Rate Pass_Fail
0                      31        68.267841      Pass
1                      16        78.222927      Fail
2                      21        87.525096      Fail
3                      27        92.076483      Pass
4                      37        98.655517      Pass
..                    ...              ...       ...
703                    14        84.658761      Fail
704                    35        60.278990      Pass
705                    25        98.384969      Fail
706                    21        96.148012      Pass
707                    22        80.404392      Fail

[708 rows x 3 columns]

In [31]:
y = LabelEncoder().fit_transform(df["Pass_Fail"])

In [32]:
y

array([1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0,
       1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1,
       0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0,
       1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0,
       0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1,
       0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1,

In [33]:
updated_df.columns

Index(['Study_Hours_per_Week', 'Attendance_Rate', 'Pass_Fail'], dtype='object')

In [34]:
updated_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 708 entries, 0 to 707
Data columns (total 3 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   Study_Hours_per_Week  708 non-null    int64  
 1   Attendance_Rate       708 non-null    float64
 2   Pass_Fail             708 non-null    object 
dtypes: float64(1), int64(1), object(1)
memory usage: 16.7+ KB


In [39]:
df["Attendance_Rate"]= df["Attendance_Rate"].astype(int)

In [40]:
updated_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 708 entries, 0 to 707
Data columns (total 3 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   Study_Hours_per_Week  708 non-null    int64  
 1   Attendance_Rate       708 non-null    float64
 2   Pass_Fail             708 non-null    object 
dtypes: float64(1), int64(1), object(1)
memory usage: 16.7+ KB


In [41]:
from sklearn.preprocessing import StandardScaler

In [42]:
scale =StandardScaler()

In [47]:
s = df[['Study_Hours_per_Week', 'Attendance_Rate']]

In [58]:
scaled=scale.fit_transform(s)

In [59]:
scaled_col =pd.DataFrame(scaled,columns=['Study_Hours_per_Week', 'Attendance_Rate'])

In [60]:
scaled_col

Study_Hours_per_Week  Attendance_Rate
0                0.548640        -0.696308
1               -1.142177         0.029953
2               -0.578571         0.683588
3                0.097755         1.046718
4                1.224966         1.482474
..                    ...              ...
703             -1.367619         0.465710
704              0.999524        -1.277316
705             -0.127687         1.482474
706             -0.578571         1.337222
707             -0.465850         0.175205

[708 rows x 2 columns]

In [37]:
from sklearn.neighbors import KNeighborsClassifier

In [14]:
kc = KNeighborsClassifier(n_neighbors=3)

In [61]:
from sklearn.model_selection import train_test_split

In [62]:
x_train,x_test,y_train,y_test =train_test_split(scaled_col,y,test_size=0.2,random_state=42)

In [64]:
kc.fit(x_train,y_train)

KNeighborsClassifier(n_neighbors=3)

In [65]:
y_pred = kc.predict(x_test)

In [66]:
y_pred

array([0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0,
       1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1,
       0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0,
       0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 0, 1, 0, 0, 1, 1, 1, 0, 1])

In [67]:
y_test

array([0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0,
       0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1,
       0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 1])

In [68]:
from sklearn.metrics import accuracy_score

In [69]:
accuracy_score(y_pred,y_test)

0.7253521126760564